### ISSUE TITLE
totalStakes is no longer being returned by the GenesisProtocol.Proposal struct

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc#421]
In commit 3e7194def1bcfbd687e6300f5cbdcdc81c339c20 the Proposal totalStakes variable was changed to an array, and now the value of it is not being returned when i try to look up a Proposal. any thoughts why?  @dragonfly thought that maybe the array is not being initialized correctly? https://medium.com/loom-network/ethereum-solidity-memory-vs-storage-how-to-initialize-an-array-inside-a-struct-184baf6aa2eb

**Comment by orenyodfat** [comment]
Please use ProposalStatus to get the
totalStake

**Comment by dkent600** [comment]
@orenyodfat 

> Please use ProposalStatus to get the totalStake

Is that suggestion a work-around or permanent requirement?

Just out of curiosity, any idea why this array is appearing?

**Comment by orenyodfat** [comment]
The reason for the array is to make the solc happy ,otherwise it complains about the proposal struct size by "InternalCompilerError: Stack too deep, try removing local variables. " 

I saw there is an open issue on solidity re similar issue and it might be solved in future versions.
So till then , this is the solution to get totalStakersStakes and totalRedeemableStakes.
