### ISSUE TITLE
Add _beneficiary to the RedeemerRedeem event logs

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc#499]
This will make things significantly easier in alchemy

**Comment by orenyodfat** [comment]
How about watching the events from  GenesisProtocol and Contribution Reward .
This issue should be on Alchemy.

**Comment by dkent600** [comment]
An argument can be made that this is a "helper" contract, so it should be helpful  ;-)

I would add both _avatar and _crBeneficiary to the event, both indexed.  Really simple to do.

**Comment by tibetsprague** [comment]
following those events is going to make it a lot more complicated and hard to correctly track redemptions in alchemy. we can do it, but I really don't understand the resistance to doing this simple fix in Arc, one that seems obvious. Otherwise the RedeemerRedeem event is almost useless, so why have it at all?

**Comment by dkent600** [comment]
> I agree that If this event is useless/confusing we might consider to remove
it.

The easier solution, one that would seem to work perfectly well, is to the add avatar and crBeneficiary to the event.  (We need avatar because Genesis Alpha is not the only DAO that may be using this contract, and pulling the avatar from the proposal wold be onerous on performance.)

If there is indeed some advantage to independently tracking the separate GP and CR events, Alchemy can do that when the priority arises, but that is a larger project, and time is currently of the essence for Alchemy.

**Comment by dkent600** [comment]
The fact that some other app might cause a redemption is a compelling enough reason to me for us to remove the event altogether.

**Comment by tibetsprague** [comment]
yeah i guess we should probably remove it
