### ISSUE TITLE
Don't require passing in a proposalId to GenesisProtocol.threshold

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc#500]
The current threshold should be the same for the whole DAO, not per proposal. Can't we track that param by the avatar so I don't have to look up the new value for every proposal after every stake?

**Comment by orenyodfat** [comment]
It is by a proposal to prevent the case having the dao change its param during the proposal phase.
Though giving it another thought , we might make this function internal as the threshold calculation can be done off chain in the client side saving tx and gas.

**Comment by dkent600** [comment]
If the threshold logic is part of the definition of the GenesisProtocol contract, then I would suggest leaving its calculation in the contract and allowing contract users to continue to be able to obtain it from the contract.  Those users always have the option to compute the value offline if they want to.

**Comment by dkent600** [comment]
In Alchemy's case, perhaps it is possible to prohibit the case where "the dao change its param during the proposal phase".

So I wonder if it would it be possible to accommodate this request by allowing the caller to submit a null proposalId and then receive the computation derived directly from the controller rather than via the proposal?

**Comment by orenyodfat** [comment]
If the user would like get the threshold it should calculate that off chain
and arc.js should support that.

**Comment by orenyodfat** [comment]
The correct result can be calculated off chain
