### ISSUE TITLE
Best practices for proposal execution?

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/arc#641]
I'm wondering what the best practice is for executing proposals. Should the execution logic for a proposal be within the `executeProposal` function like in [SchemeRegistrar.sol](https://github.com/daostack/arc/blob/f5e16c2b78d85e7290b32b145524667e80c405e3/contracts/universalSchemes/SchemeRegistrar.sol#L60), or should the logic run in another method that's paid for by an outside user to execute like in [ContributionReward.sol](https://github.com/daostack/arc/blob/f5e16c2b78d85e7290b32b145524667e80c405e3/contracts/universalSchemes/ContributionReward.sol#L83)?

Should the scheme developer *prefer* to do it within `executeProposal` whenever possible, but use the alternative method when there are other limiting factors that prohibit it from being done (too expensive, etc)?

**Comment by ben-kaufman** [comment]
I think the reason for the difference between the two is because in the Contribution Reward, the DAO might not have the funds for the reward on hand, but we would not want the execution itself to fail because of that. Also there might be multiple redeem periods for a Contribution Reward so this necessarily means the redeeming will have to be separately executed.
I'd say that generally it's better to just put the execution in the `executeProposal` function like with Scheme Registrar but this is not always possible, and not very important.

**Comment by dOrgJelli** [comment]
Awesome, thank for the answer @ben-kaufman!
